
const constants = {
    GET_USERS: 'GET_USERS',
    GET_USERS_FULFILLED: 'GET_USERS_FULFILLED',
    GET_USERS_REJECTED: 'GET_USERS_REJECTED',
    GET_SINGLE_USER: 'GET_SINGLE_USER',
    GET_SINGLE_USER_FULFILLED: 'GET_SINGLE_USER_FULFILLED',
    GET_SINGLE_USER_REJECTED: 'GET_SINGLE_USER_REJECTED',
    GET_SEARCH_USER: 'GET_SEARCH_USER',
    HIDE_SNACKBAR: "HIDE_SNACKBAR",
    CHANGE_MODAL_STATE: "CHANGE_MODAL_STATE",
    SELECTED_ITEM: "SELECTED_ITEM"
}

export default constants;